---
parent: 'test_cases/test_branch_origin_extended_conformance_install.yml'
overrides:
  junit_analysis: True
  sync:
    - "openshift,origin"
    - "openshift,aos-cd-jobs=master"
    - "openshift,image-registry"
    - "openshift,kubernetes-metrics-server"
    - "openshift,origin-web-console-server"
